added steps to verify logging container

diff --git a/.github/workflows/app-logging.yml b/.github/workflows/app-logging.yml
--- a/.github/workflows/app-logging.yml
+++ b/.github/workflows/app-logging.yml
@@ -10,7 +10,6 @@ jobs:
 
   build:
 
-    name: build pims-logging
     runs-on: ubuntu-latest
     env:
       SLEEP_TIME: 60
@@ -38,45 +37,20 @@ jobs:
       uses: jakejarvis/wait-action@master
       with:
         time: '180s'
+    - uses: actions/checkout@v1
+    - name: Check Extracted Logs
+      run: |
+        docker cp pims-logging:/logging/pims* /tmp/ 
+        if [[ "$(ls -A /tmp//pims* 2>/dev/null | wc -l)" != "0" ]]; then
+            ls -A /tmp/pims* && rm -f /tmp/pims*
+        else
+            echo "There's an error capturing pims logs" && exit 1
+        fi
     - name: Check running containers
       run: docker ps -a
     - name: Check pims-logging logs
       run: docker logs pims-logging
-          
-  verify_build:
-    
-    needs: build
-    name: verify build
-    runs-on: ubuntu-latest
-    container: pims-logging:latest
-    steps:
-    - uses: actions/checkout@v1
-    - name: Sleep for 180 seconds
-      uses: jakejarvis/wait-action@master
-      with:
-        time: '180s'
-    - name: Check Extracted Logs
-      run: | 
-        if [[ "$(ls -A /logging/pims* 2>/dev/null | wc -l)" != "0" ]]; then
-            ls -A /logging/pims*
-        else
-            echo "There's an error capturing pims logs" && exit 1
-        fi
-      working-directory: ./logging
-      
-  stop_container:
-   
-    needs: [build, verify_build]
-    name: stop container
-    runs-on: ubuntu-latest
-    env:
-       working-directory: ./openshift/4.0/templates/Logging
-        
-    steps:
-    - uses: actions/checkout@v1
     - name: Stop containers
       if: always()
       run: docker-compose -f "docker-compose.yml" down
       working-directory: ${{env.working-directory}}
-    
-      
