scan with aquaSec trivy

diff --git a/.github/workflows/trivy-analysis.yml b/.github/workflows/trivy-analysis.yml
--- a/.github/workflows/trivy-analysis.yml
+++ b/.github/workflows/trivy-analysis.yml
@@ -50,7 +50,7 @@ jobs:
         format: 'template'
         template: '@/contrib/sarif.tpl'
         exit-code: '1'
-        ignore-unfixed: false
+        ignore-unfixed: true
         vuln-type: 'os,library'
         severity: 'CRITICAL,HIGH'
         output: 'trivy-results.sarif'
@@ -59,3 +59,30 @@ jobs:
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: 'trivy-results.sarif'
+        
+    - name: Build db-schema and load schema
+      run: docker run -d -p 5433:1433 --name db-schema --env-file ./.env docker.io/my-organization/my-app:${{ github.sha }}
+      working-directory: ${{env.working-directory}}
+    - name: Wait on the sqlserver process
+      uses: jakejarvis/wait-action@master
+      with:
+        time: '180s'        
+    - name: Check running containers
+      run: docker ps -a
+    - name: Check pims-database logs
+      run: docker logs db-schema
+    - name: Check schema build
+      run: |
+        docker cp db-schema:/tmp/log.txt .
+        result="$(cat log.txt)"
+        if [[ "$result" != "0" ]]; then
+            echo "$result record loaded";
+        else
+            echo "There's an error loading schema" && exit 1 ;
+        fi
+      working-directory: ${{env.working-directory}}
+            
+    - name: Stop containers
+      if: always()
+      run: docker stop db-schema
+      working-directory: ${{env.working-directory}}
